### ISSUE TITLE
Antwort vom Server enthält keine JSON-formatierten Daten

### ISSUE THREAD

**Issue by JoBilert** [ola-ct/ctpwdgen-server#1]
Hallo, ich habe versucht mich an die Anleitung aus c't 23/2015 zu halten (verwende aber apache).

Wenn ich die VErbindung zu meinem Server teste bekomme ich in Qt-Sesam ein rotes Ausrufezeichen und als Tooltip die obige Meldung.
"Antwort vom Server enthält keine JSON-formatiereten Daten"
Was habe ich falsch gemacht?

Gruß Bilert

**Comment by 607011** [comment]
@TalmarGrosskotz Was zeigt der Browser an, wenn Sie `https://example.com/ctSESAM/ajax/read.php`  darin aufrufen? (Die URL ist freilich durch die tatsächliche zu ersetzen.)

**Comment by JoBilert** [comment]
Wenn ich die read.php aufrufe, erscheint zunächst eine Eingabemaske für Benutzername und Kennwort. Nachdem ich keines vergeben habe lasse ich die Felder leer. Daraufhin bietet Firefox die read.php zum Download an.

**Comment by 607011** [comment]
Und was steht in dieser Datei?

**Comment by JoBilert** [comment]
Die geöffnete read.php enthält nur eine Zeile:

{"status":"ok"}

Mehr is nicht drin.

**Comment by 607011** [comment]
Das sieht eigentlich gut aus. Mmmhh …

**Comment by 607011** [comment]
@TalmarGrosskotz Mit welcher Version von Qt-SESAM arbeiten Sie? Verwenden Sie Windows?

**Comment by JoBilert** [comment]
Nutze den neusten 64-bit Build für Windows den ich von der github-Seite aus finden konnte, auf Windows10.

Am 18. Oktober 2015 13:23:48 MESZ, schrieb Oliver Lau notifications@github.com:

> @TalmarGrosskotz Mit welcher Version von Qt-SESAM arbeiten Sie?
> Verwenden Sie Windows?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ola-ct/ctSESAM-server/issues/1#issuecomment-149004156

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by 607011** [comment]
Zur Fehlereingrenzung wäre es schön, wenn Sie den mal deinstallieren und stattdessen die 32-Bit-Version verwenden. Ich habe da so eine Ahnung …

Danke vorab.

**Comment by JoBilert** [comment]
Version 2.1.0 beta 2

Am 18. Oktober 2015 13:23:48 MESZ, schrieb Oliver Lau notifications@github.com:

> @TalmarGrosskotz Mit welcher Version von Qt-SESAM arbeiten Sie?
> Verwenden Sie Windows?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ola-ct/ctSESAM-server/issues/1#issuecomment-149004156

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by JoBilert** [comment]
Werde ich später testen. Geh jetzt erstmal mit meinen Kids ins Hallenbad :) Vielen Dank schon mal für den tollen Support.

**Comment by 607011** [comment]
Viel Spaß!

Nach der Rückkehr bitte mal diese Version ausprobieren: **[Download](https://github.com/ola-ct/Qt-SESAM/releases/download/v2.1.0-BETA2/20151018-QtSESAM-2.1.0-BETA2-portable-x86.zip)**. Sie gibt eine detailliertere Warnmeldung aus.

Das Entpacken der ZIP-Datei in ein beliebiges Verzeichnis genügt zur Installation. Nach dem Testen können Sie das Verzeichnis gefahrlos wieder löschen. Die bis dahin angelegten Domain-Einstellungen sind damit auch gelöscht.

**Comment by JoBilert** [comment]
Keine Warnmeldung :) Die Version ging, lag also irgendwie am 64-Bit?

Am 18.10.2015 um 13:52 schrieb Oliver Lau:

> Viel Spaß!
> 
> Nach der Rückkehr bitte mal diese Version ausprobieren: _Download
> https://github.com/ola-ct/Qt-SESAM/releases/download/v2.1.0-BETA2/20151018-QtSESAM-2.1.0-BETA2-portable-x86.zip_.
> Sie gibt eine detailliertere Warnmeldung aus.
> 
> Das Entpacken der ZIP-Datei in ein beliebiges Verzeichnis genügt zur
> Installation. Nach dem Testen können Sie das Verzeichnis gefahrlos
> wieder löschen. Die bis dahin angelegten Domain-Einstellungen sind damit
> auch gelöscht.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ola-ct/ctSESAM-server/issues/1#issuecomment-149005608.

---

Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by 607011** [comment]
Gut, gut, dann hat sich mein Verdacht also bestätigt ;-)

Sie haben doch eine HTTPS-Verbindung verwendet, oder …?

**Comment by JoBilert** [comment]
Ja genau habe eine https-Verbindung zu meinem Apache-Server.

**Comment by 607011** [comment]
Der Sync-Server trägt keine Schuld. Wie auch? Der ist ja zu dumm, um Fehler zu begehen ;-)

Das Problem liegt vermutlich in der 64-Bit-Version der SSL-Bibliothek (libeay32.dll und ssleay32.dll). Die scheint einige Protokolle nicht zu unterstützen.

Ich habe von [Qt-SESAM 2.1.0 BETA2](https://github.com/ola-ct/Qt-SESAM/releases/tag/v2.1.0-BETA2) prophylaktisch alle 64-Bit-Downloads entfernt.

Vielen Dank für Ihre Unterstützung, @TalmarGrosskotz
