### ISSUE TITLE
Nginx will keine basic auth

### ISSUE THREAD

**Issue by Microgamer** [ola-ct/ctpwdgen-server#3]
Hallo,

jetzt habe ich aber ein Problem, welches ich nicht lösen kann.
Ich habe den Server wie im Wiki beschrieben eingerichtet und wollte dann noch wie im c't Artikel beschrieben Basic auth benutzen. Leider geht dies nicht. Es ist alles genau so wie im Artikel beschrieben eingerichtet, aber es wird kein Dialog angezeigt. Hat jemand eine Ahnung, woran das liegen könnte?

Gruß

**Comment by 607011** [comment]
@pinae to the rescue!

**Comment by pinae** [comment]
Ich schätze mal, es geht um diesen Artikel: http://www.heise.de/ct/ausgabe/2015-23-Den-Webserver-Nginx-fuer-HTTPS-einrichten-2842005.html

Ich verstehe das so, dass nach Aufruf von read.php vom c't SESAM Server im Browser kein Anmeldedialog kam. Da sollte ein Anmeldedialog erscheinen und nach Eingabe der Accountdaten ein Download starten. In der heruntergeladenen Textdatei sollte nur `{"status": "ok"}` stehen.

Wenn das nicht so funktioniert, stimmt vermutlich mit der Nginx-Konfiguration etwas nicht. Um mehr dazu zu sagen, müsste ich die V-Host-Konfiguration mal sehen (Domainnamen einfach auf example.com ändern). 

Was passiert denn genau? Startet der Download ohne Anmeldefenster? Kommt eine Fehlermeldung?

**Comment by Microgamer** [comment]
Hat sich erledigt. Habe als Servername die lokale IP und nicht die Domain eingetragen. Bin grade per VPN im Netzwerk und über die lokale IP ging alles. Name geändert und es ging.
