### ISSUE TITLE
HTTP-Authentifizierung mit FastCGI

### ISSUE THREAD

**Issue by stelas** [ola-ct/ctpwdgen-server#4]
Hi,

in Shared-Webhosting-Umgebungen wird PHP zumeist per FastCGI angebunden. Um die HTTP-Authentifizierung dort ans Laufen zu bringen, ist am Sync-Server folgende kleine Ergänzung erforderlich:

.htaccess

```
RewriteEngine on
RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization},last]
```

ajax/globals.php - am Anfang in assert_basic_auth() einfügen:

``` php
    if (preg_match('/Basic\s+(.*)$/i', $_SERVER['HTTP_AUTHORIZATION'], $matches)) {
        list($name, $password) = explode(':', base64_decode($matches[1]));
        $_SERVER['PHP_AUTH_USER'] = strip_tags($name);
        $_SERVER['PHP_AUTH_PW'] = strip_tags($password);
    }
```

Wäre schön, wenn es in die nächste Revision einfließen würde. :smile:

Gruß Steffen

**Comment by 607011** [comment]
Danke für die Info. Ich nehme gerne Pull Requests entgegen ;-)

**Comment by 607011** [comment]
Resolved with pull request #5

**Comment by q6276270** [comment]
Hallo,
es wäre sicherlich nett für weniger erfahrene Benutzer wie mich, wenn man die .htaccess Datei zum Repository hinzufügen könnte. Ich saß gerade sehr lange daran, den client mit dem server zu verbinden, weil ich das oben genannte Problem hatte, es dafür aber keinerlei Hinweis gab.
Gruß
