### ISSUE TITLE
Serverfehler bei Aufruf des installscripts

### ISSUE THREAD

**Issue by mporwoll** [ola-ct/ctpwdgen-server#7]
Hallo,

habe die Installation wie im wiki erläutert vollzogen, bekomme allerdings beim Aufruf der install.php einen internen serverfehler 500 ausgeworfen. Was mache ich falsch?

Gruß

**Comment by 607011** [comment]
Was sagen denn die Log-Dateien des Webservers?

**Comment by mporwoll** [comment]
Ja, die sagen so einiges...:

Stack trace:
[Tue Mar 22 17:23:01 2016] [error] [client 88.152.187.0] #0 /pages/b5/9a/d0008698/home/htdocs/site/prwsesam/ajax/globals.php(64): PDO->__construct('sqlite:/site/pr...', NULL, NULL, Array)
[Tue Mar 22 17:23:01 2016] [error] [client 88.152.187.0] #1 /pages/b5/9a/d0008698/home/htdocs/site/prwsesam/ajax/install.php(2): require_once('/pages/b5/9a/d0...')
[Tue Mar 22 17:23:01 2016] [error] [client 88.152.187.0] #2 {main}
[Tue Mar 22 17:23:01 2016] [error] [client 88.152.187.0]   thrown in /pages/b5/9a/d0008698/home/htdocs/site/prwsesam/ajax/globals.php on line 64
[Tue Mar 22 17:23:01 2016] [error] [client 88.152.187.0] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [14] unable to open database file' in /pages/b5/9a/d0008698/home/htdocs/site/prwsesam/ajax/globals.php:64
[Tue Mar 22 17:23:01 2016] [error] [client 88.152.187.0] Stack trace:
[Tue Mar 22 17:23:01 2016] [error] [client 88.152.187.0] #0 /pages/b5/9a/d0008698/home/htdocs/site/prwsesam/ajax/globals.php(64): PDO->__construct('sqlite:/site/pr...', NULL, NULL, Array)
[Tue Mar 22 17:23:01 2016] [error] [client 88.152.187.0] #1 /pages/b5/9a/d0008698/home/htdocs/site/prwsesam/ajax/install.php(2): require_once('/pages/b5/9a/d0...')
[Tue Mar 22 17:23:01 2016] [error] [client 88.152.187.0] #2 {main}
[Tue Mar 22 17:23:01 2016] [error] [client 88.152.187.0]   thrown in /pages/b5/9a/d0008698/home/htdocs/site/prwsesam/ajax/globals.php on line 64
[Tue Mar 22 17:54:08 2016] [error] [client 88.152.187.0] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [14] unable to open database file' in /pages/b5/9a/d0008698/home/htdocs/site/prwsesam/ajax/globals.php:64
[Tue Mar 22 17:54:08 2016] [error] [client 88.152.187.0] Stack trace:
[Tue Mar 22 17:54:08 2016] [error] [client 88.152.187.0] #0 /pages/b5/9a/d0008698/home/htdocs/site/prwsesam/ajax/globals.php(64): PDO->__construct('sqlite:/site/pr...', NULL, NULL, Array)
[Tue Mar 22 17:54:08 2016] [error] [client 88.152.187.0] #1 /pages/b5/9a/d0008698/home/htdocs/site/prwsesam/ajax/install.php(2): require_once('/pages/b5/9a/d0...')
[Tue Mar 22 17:54:08 2016] [error] [client 88.152.187.0] #2 {main}
[Tue Mar 22 17:54:08 2016] [error] [client 88.152.187.0]   thrown in /pages/b5/9a/d0008698/home/htdocs/site/prwsesam/ajax/globals.php on line 64
[Tue Mar 22 17:54:46 2016] [error] [client 88.152.187.0] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

**Comment by 607011** [comment]
Der Pfad zur Datenbank scheint falsch zu sein oder dem Webserver fehlen die Schreibrechte für dieses Verzeichnis.

**Comment by mporwoll** [comment]
Ja, Rookie-Fehler :) es war der Pfad!
